### ISSUE TITLE
max data export

### ISSUE THREAD

**Issue by jaf0** [faelys/pebble-health-export#1]
I just tried doing an export, and it seems to be starting 14 days ago. Is there a way export more than that?

**Comment by faelys** [comment]
I don't know of any way to export more than that.

On the first export, or when checking the "resend everything", it asks for all Pebble Health data available, and sends it.

In my experiments, I found it seems to go about two weeks back, sometimes a bit more. My theory is that the watch stores two full weeks of health data and the "current" week, overwriting the oldest store week on week change. So you would go 14 to 20 days back depending on when you try it.

I'm not aware of any way to access older data, even though it seems to be somehow stored on the phone (but maybe in an unrecoverably processed state).

**Comment by jaf0** [comment]
ah. that makes sense...
