### ISSUE TITLE
Since Pebble App 4.4 update, upload (POST) stopped working

### ISSUE THREAD

**Issue by EyckWigo** [faelys/pebble-health-export#10]
On iPhone, it behaves just like before latest pebble-health-export update ( ie it goes through first progress bar ( collecting data at rate ~200-300/min )) but then in hangs when it comes to uploading it to remote server.

**Comment by brianswenson** [comment]
I am not having any problems after the update.  Maybe try reloading the pebble-health-export app and double check the settings.

**Comment by faelys** [comment]
I think I have been using the version 4.4 for at least several days, and I don't have any upload problem either.

I mentioned somewhere I wanted to try to improve the error feedback of the app, to have at least some clue on what is going wrong, but I faced the problem that the XMLHttpRequest seem very bad at providing any error condition: I couldn't get it call any error-related callback, and polling its status never returned anything meaningful. So I don't even know how to diagnose the problem without diving deep with tools like tcpdump.

**Comment by EyckWigo** [comment]
I tried re-loading the app, and also re-entering URL parameters, but it stops at "DONE 2017-05-10 16:19" and then nothing happens.

I'm looking with tcpdump on target server, but I'm not getting any packets getting there, to it looks just like it did before ( on iPhone it would hang there, on Android people were saying that it works OK ).

**Comment by EyckWigo** [comment]
And this is what I'm getting from 'pebble logs':
 pkjs> Error: Pebble Health Export: Error: String of HEX type contains invalid characters at line 390 in pebble-js-app.js

**Comment by EyckWigo** [comment]
...and then when I changed output format it said this:  
 pkjs> Error: Pebble Health Export: Error: outputFormat must be HEX, B64, or BYTES at line 389 in pebble-js-app.js
and after I changed it to "Bytes" it started working.
