### ISSUE TITLE
Will Heartrate data be made available

### ISSUE THREAD

**Issue by srmchargue** [faelys/pebble-health-export#8]
I probably should have reviewed the Pebble API first to find out if it was even possible. But since I finally got my pull to work to google sheets, I wanted to say THANKS for making this app and see if Heartrate might be available in the future.

Again Thanks!

**Comment by faelys** [comment]
It is possible and it is even already done. It looks like I missed updating the documentation though, but if you have installed the version 1.1 from the Pebble App Store, you should already have an 8th column with the number of heartbeats in the minute designated by the line.

Not having the hardware, I haven't tested it myself, but I do have the 8th column, only with 0 everywhere.

**Comment by srmchargue** [comment]
I guess I should have noticed there was an extra column there. Sorry for the dumb question. SWEET! Love your app!
